# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-node:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Add .npmrc
          command: |
              echo "@bestowinc:registry=https://npm.pkg.github.com/" > ~/.npmrc
              echo "//npm.pkg.github.com/:_authToken=\"$GITHUB_TOKEN\"" >> ~/.npmrc
              npm set @bestowinc:registry https://npm.pkg.github.com
      - run:
          name: Install
          command: echo "Fake success"

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default:
    jobs:
    # - tests:
    #     filters:
    #       branches:
    #         only: /.*/
    #       tags:
    #         only: /.*/
    - build-node