# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-gcp:
    parameters:
      domain:
        type: string
    environment:
      DOMAIN: << parameters.domain >>
      BUCKET: 
    docker:
      - image: google/cloud-sdk:282.0.0-alpine
    steps:
      - run: apk add --no-cache git make openssh
      - checkout
      - run: gcloud auth activate-service-account --key-file=<(echo "$GOOGLE_SERVICE_ACCOUNT_KEY")
      - attach_workspace:
          at: .
      - run: gsutil -m rsync -r build/ "gs://$(Bucket)/"    



# Invoke jobs via w-gcoorkflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  default:
    jobs:
      - deploy_gcp:
          name: deploy-gcp-qa-demo
          domain: protect-lite.qa.bestow.com
          context: gcp-policy-platform-qa
          filters:
            branches:
              only: develop
